const UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122 Safari/537.36";
async function getJson(url,headers={}){const r=await fetch(url,{headers:{"User-Agent":UA,Accept:"application/json",...headers},signal:AbortSignal.timeout(25000)});const t=await r.text();try{return JSON.parse(t)}catch{throw new Error("El scraper no devolvió JSON.")}}
function abs(url){if(!url)return"";return String(url).startsWith("http")?String(url):`https://www.tikwm.com${url}`}
export function youtubeId(input){try{const u=new URL(input);if(u.hostname.includes("youtu.be"))return u.pathname.slice(1,12);if(u.searchParams.get("v"))return u.searchParams.get("v");const m=u.pathname.match(/\/shorts\/([\w-]{6,})/);if(m)return m[1]}catch{}return""}
export async function youtubeScrape(input,type="video"){const id=youtubeId(input);if(!id)throw new Error("Pega un enlace válido de YouTube.");const page=`https://www.youtube.com/watch?v=${id}`,o=await getJson(`https://www.youtube.com/oembed?url=${encodeURIComponent(page)}&format=json`).catch(()=>({}));let downloadUrl="",source="oembed";try{const p=await getJson(`https://pipedapi.kavin.rocks/streams/${id}`);downloadUrl=type==="audio"?p.audioStreams?.[0]?.url||"":p.videoStreams?.find(s=>s.videoOnly===false)?.url||p.videoStreams?.[0]?.url||"";if(downloadUrl)source="piped"}catch{}return{id,title:o.title||"",author:o.author_name||"",thumbnail:o.thumbnail_url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,type,downloadUrl,source,page}}
export async function tiktokScrape(url){if(!/tiktok\.com/i.test(url))throw new Error("Pega un enlace válido de TikTok.");const j=await getJson(`https://www.tikwm.com/api/?url=${encodeURIComponent(url)}&hd=1`,{Referer:"https://www.tikwm.com/"}),d=j.data;if(!d)throw new Error(j.msg||"No se pudo leer ese TikTok.");return{id:d.id||"",title:d.title||"",author:d.author?.nickname||d.author?.unique_id||"",username:d.author?.unique_id||"",cover:abs(d.cover||d.origin_cover||""),views:d.play_count||0,likes:d.digg_count||0,videoUrl:abs(d.hdplay||d.play||d.wmplay||""),images:Array.isArray(d.images)?d.images.map(abs):[],audioUrl:abs(d.music||""),duration:d.duration||0,source:"tikwm"}}
export async function tiktokProfile(user){const username=String(user||"").replace(/^@/,"").trim();if(!/^[A-Za-z0-9._]{2,24}$/.test(username))throw new Error("Usuario de TikTok no válido.");const j=await getJson(`https://www.tikwm.com/api/user/info?unique_id=${encodeURIComponent(username)}`,{Referer:"https://www.tikwm.com/"}),u=j.data?.user||j.data;if(!u)throw new Error("No se encontró ese perfil.");return{username:u.uniqueId||username,nickname:u.nickname||"",signature:u.signature||"",followers:u.followerCount||u.stats?.followerCount||0,following:u.followingCount||0,videos:u.videoCount||0,avatar:u.avatarLarger||u.avatarMedium||"",source:"tikwm"}}
export async function tiktokSearch(query){const q=String(query||"").trim();if(q.length<2)throw new Error("Escribe una búsqueda de al menos 2 letras.");const j=await getJson(`https://www.tikwm.com/api/feed/search?keywords=${encodeURIComponent(q)}&count=8`,{Referer:"https://www.tikwm.com/"}),list=j.data?.videos||j.data||[];return(Array.isArray(list)?list:[]).slice(0,8).map(x=>({id:x.video_id||x.id||"",title:x.title||"",author:x.author?.nickname||x.author?.unique_id||"",cover:abs(x.cover||x.origin_cover||""),url:x.play?abs(x.play):"",page:x.video_id?`https://www.tiktok.com/@${x.author?.unique_id||"user"}/video/${x.video_id}`:""}))}
export async function instagramScrape(url){if(!/instagram\.com/i.test(url))throw new Error("Pega un enlace válido de Instagram.");const j=await getJson(`https://api-faa.my.id/faa/instagram?url=${encodeURIComponent(url)}`),r=j.result||j.data||j,m=r.medias||r.media||r.url||[],items=Array.isArray(m)?m.map(x=>({url:x.url||x,type:x.type||(/mp4/i.test(x.url||x)?"video":"image")})).filter(x=>x.url):[{url:r.hd||r.sd||r.url||"",type:"video"}].filter(x=>x.url);if(!items.length)throw new Error("No se pudo extraer el medio de Instagram.");return{title:r.title||r.caption||"",author:r.author||r.username||"",items,source:"faa"}}
export async function facebookScrape(url){if(!/facebook\.com|fb\.watch/i.test(url))throw new Error("Pega un enlace válido de Facebook.");const j=await getJson(`https://api-faa.my.id/faa/facebook?url=${encodeURIComponent(url)}`),r=j.result||j.data||{},videoUrl=r.hd||r.sd||r.url||"";if(!videoUrl)throw new Error("No se encontró video en ese enlace.");return{title:r.title||"",videoUrl,thumbnail:r.thumbnail||r.thumb||"",source:"faa"}}
export async function stickerFromUrl(url){if(!/^https?:\/\//i.test(url))throw new Error("Falta una URL de imagen.");const r=await fetch(url,{headers:{"User-Agent":UA},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error("No se pudo abrir la imagen.");const mime=r.headers.get("content-type")||"";if(!/^image\//i.test(mime))throw new Error("La URL no apunta a una imagen.");return{sourceUrl:url,mime,note:"Imagen válida. El panel devuelve el medio listo para usarlo como sticker."}}
