import fs from "node:fs"; import path from "node:path";
const DATA_PATH=path.join(process.cwd(),"data","db.json");
function emptyDb(){return{users:[],keys:[],usage:[]}}
function databaseUrl(){return process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.DATABASE_URL_UNPOOLED||process.env.POSTGRES_URL_NON_POOLING||process.env.POSTGRES_PRISMA_URL||""}
export function storageMode(){return databaseUrl()?"postgres":"file"}
let neonSql=null,schemaReady=false;
async function sql(){const url=databaseUrl();if(!url)return null;if(!neonSql){const{neon}=await import("@neondatabase/serverless");neonSql=neon(url)}if(!schemaReady){await neonSql`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user', created_at TEXT NOT NULL, provider TEXT, provider_id TEXT)`;await neonSql`CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,key_value TEXT UNIQUE NOT NULL,created_at TEXT NOT NULL,last_used_at TEXT)`;await neonSql`CREATE TABLE IF NOT EXISTS api_usage (key_id TEXT NOT NULL,endpoint TEXT NOT NULL,day TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(key_id,endpoint,day))`;schemaReady=true}return neonSql}
function readFileDb(){try{if(!fs.existsSync(DATA_PATH))return emptyDb();const p=JSON.parse(fs.readFileSync(DATA_PATH,"utf8"));return{users:Array.isArray(p.users)?p.users:[],keys:Array.isArray(p.keys)?p.keys:[],usage:Array.isArray(p.usage)?p.usage:[]}}catch{return emptyDb()}}
function writeFileDb(db){fs.mkdirSync(path.dirname(DATA_PATH),{recursive:true});fs.writeFileSync(DATA_PATH,JSON.stringify(db,null,2))}
export function databaseReady(){return databaseUrl()?true:process.env.VERCEL!=="1"}
export async function countUsers(){const q=await sql();if(q){const r=await q`SELECT COUNT(*)::int AS n FROM users`;return Number(r[0]?.n||0)}return readFileDb().users.length}
export async function findUserByEmail(email){const q=await sql();if(q){const r=await q`SELECT * FROM users WHERE email=${email} LIMIT 1`;return r[0]||null}return readFileDb().users.find(u=>u.email===email)||null}
export async function findUserByProvider(provider,id){const q=await sql();if(q){const r=await q`SELECT * FROM users WHERE provider=${provider} AND provider_id=${id} LIMIT 1`;return r[0]||null}return readFileDb().users.find(u=>u.provider===provider&&u.provider_id===id)||null}
export async function findUserByUsername(username){const q=await sql();if(q){const r=await q`SELECT * FROM users WHERE username=${username} LIMIT 1`;return r[0]||null}return readFileDb().users.find(u=>u.username===username)||null}
export async function findUserById(id){const q=await sql();if(q){const r=await q`SELECT * FROM users WHERE id=${id} LIMIT 1`;return r[0]||null}return readFileDb().users.find(u=>u.id===id)||null}
export async function createUser(user){const q=await sql();if(q){await q`INSERT INTO users(id,username,email,password_hash,role,created_at,provider,provider_id) VALUES(${user.id},${user.username},${user.email},${user.password_hash},${user.role},${user.created_at},${user.provider||"password"},${user.provider_id||""})`;return user}const db=readFileDb();db.users.push(user);writeFileDb(db);return user}
export async function updateUserPassword(id,h){const q=await sql();if(q){await q`UPDATE users SET password_hash=${h} WHERE id=${id}`;return}const db=readFileDb(),u=db.users.find(x=>x.id===id);if(u)u.password_hash=h;writeFileDb(db)}
export async function listKeys(userId){const q=await sql();if(q)return q`SELECT * FROM api_keys WHERE user_id=${userId} ORDER BY created_at DESC`;return readFileDb().keys.filter(k=>k.user_id===userId)}
export async function countKeys(userId){return(await listKeys(userId)).length}
export async function createKey(row){const q=await sql();if(q){await q`INSERT INTO api_keys(id,user_id,name,key_value,created_at,last_used_at) VALUES(${row.id},${row.user_id},${row.name},${row.key_value},${row.created_at},${row.last_used_at})`;return row}const db=readFileDb();db.keys.push(row);writeFileDb(db);return row}
export async function findKeyByValue(v){const q=await sql();if(q){const r=await q`SELECT * FROM api_keys WHERE key_value=${v} LIMIT 1`;return r[0]||null}return readFileDb().keys.find(k=>k.key_value===v)||null}
export async function findKeyById(id,userId){const q=await sql();if(q){const r=await q`SELECT * FROM api_keys WHERE id=${id} AND user_id=${userId} LIMIT 1`;return r[0]||null}return readFileDb().keys.find(k=>k.id===id&&k.user_id===userId)||null}
export async function deleteKey(id,userId){const q=await sql();if(q){await q`DELETE FROM api_usage WHERE key_id=${id}`;await q`DELETE FROM api_keys WHERE id=${id} AND user_id=${userId}`;return}const db=readFileDb();db.keys=db.keys.filter(k=>!(k.id===id&&k.user_id===userId));db.usage=db.usage.filter(u=>u.key_id!==id);writeFileDb(db)}
export async function replaceKeyValue(id,userId,v){const q=await sql();if(q){await q`UPDATE api_keys SET key_value=${v} WHERE id=${id} AND user_id=${userId}`;return}const db=readFileDb(),k=db.keys.find(x=>x.id===id&&x.user_id===userId);if(k)k.key_value=v;writeFileDb(db)}
export async function touchKey(id){const now=new Date().toISOString(),q=await sql();if(q){await q`UPDATE api_keys SET last_used_at=${now} WHERE id=${id}`;return}const db=readFileDb(),k=db.keys.find(x=>x.id===id);if(k)k.last_used_at=now;writeFileDb(db)}
export async function getUsage(keyId,endpoint,day){const q=await sql();if(q){const r=await q`SELECT count FROM api_usage WHERE key_id=${keyId} AND endpoint=${endpoint} AND day=${day} LIMIT 1`;return Number(r[0]?.count||0)}const r=readFileDb().usage.find(u=>u.key_id===keyId&&u.endpoint===endpoint&&u.day===day);return r?r.count:0}
export async function addUsage(keyId,endpoint,day){const q=await sql();if(q){await q`INSERT INTO api_usage(key_id,endpoint,day,count) VALUES(${keyId},${endpoint},${day},1) ON CONFLICT(key_id,endpoint,day) DO UPDATE SET count=api_usage.count+1`;const r=await q`SELECT count FROM api_usage WHERE key_id=${keyId} AND endpoint=${endpoint} AND day=${day}`;return Number(r[0]?.count||1)}const db=readFileDb();let r=db.usage.find(u=>u.key_id===keyId&&u.endpoint===endpoint&&u.day===day);if(!r){r={key_id:keyId,endpoint,day,count:0};db.usage.push(r)}r.count++;writeFileDb(db);return r.count}
export async function usageForKeys(ids,day){if(!ids.length)return[];const q=await sql();if(q){const r=await q`SELECT key_id,endpoint,count FROM api_usage WHERE day=${day}`;return r.filter(x=>ids.includes(x.key_id))}return readFileDb().usage.filter(u=>u.day===day&&ids.includes(u.key_id))}
export function publicUser(u){return u?{id:u.id,username:u.username,email:u.email,role:u.role,created_at:u.created_at}:null}
